/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import appli.App;
import entities.TableAnnexe;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author gimli
 */
public class JFrameBibliotheque extends javax.swing.JFrame {

    public String[] idLivres;
    
    App app;

    /**
     * Creates new form JFrameBibliothèque
     */
    public JFrameBibliotheque() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneControle = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBibliotheque = new javax.swing.JTable();
        jButtonAjouterLivre = new javax.swing.JButton();
        jButtonDeco = new javax.swing.JButton();
        jToggleButtonSupprimerLivre = new javax.swing.JToggleButton();
        jLabelBibliotheque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 240, 241));

        jDesktopPaneControle.setBackground(new java.awt.Color(236, 240, 241));
        jDesktopPaneControle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPaneControle.setForeground(new java.awt.Color(240, 240, 240));

        jTableBibliotheque.setBackground(new java.awt.Color(236, 240, 241));
        jTableBibliotheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titre", "Auteur", "Ref", "Pages", "Edition", "Genre", "Année Ed.", "Format", "Langue", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBibliotheque.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableBibliotheque);
        jTableBibliotheque.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTableBibliotheque.getColumnModel().getColumnCount() > 0) {
            jTableBibliotheque.getColumnModel().getColumn(0).setMinWidth(150);
            jTableBibliotheque.getColumnModel().getColumn(4).setMinWidth(100);
            jTableBibliotheque.getColumnModel().getColumn(5).setMinWidth(120);
            jTableBibliotheque.getColumnModel().getColumn(7).setMinWidth(190);
            jTableBibliotheque.getColumnModel().getColumn(8).setMinWidth(90);
            jTableBibliotheque.getColumnModel().getColumn(8).setMaxWidth(50);
            jTableBibliotheque.getColumnModel().getColumn(9).setMaxWidth(30);
        }

        jButtonAjouterLivre.setBackground(new java.awt.Color(26, 188, 156));
        jButtonAjouterLivre.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAjouterLivre.setText("Ajouter livre");
        jButtonAjouterLivre.setBorderPainted(false);
        jButtonAjouterLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterLivreActionPerformed(evt);
            }
        });

        jButtonDeco.setBackground(new java.awt.Color(26, 188, 156));
        jButtonDeco.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeco.setText("Déconnexion");
        jButtonDeco.setBorderPainted(false);
        jButtonDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecoActionPerformed(evt);
            }
        });

        jToggleButtonSupprimerLivre.setBackground(new java.awt.Color(26, 188, 156));
        jToggleButtonSupprimerLivre.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonSupprimerLivre.setText(" Supprimer livre");
        jToggleButtonSupprimerLivre.setBorderPainted(false);
        jToggleButtonSupprimerLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSupprimerLivreActionPerformed(evt);
            }
        });

        jLabelBibliotheque.setText("Bibliothèque");

        jDesktopPaneControle.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneControle.setLayer(jButtonAjouterLivre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneControle.setLayer(jButtonDeco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneControle.setLayer(jToggleButtonSupprimerLivre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneControle.setLayer(jLabelBibliotheque, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneControleLayout = new javax.swing.GroupLayout(jDesktopPaneControle);
        jDesktopPaneControle.setLayout(jDesktopPaneControleLayout);
        jDesktopPaneControleLayout.setHorizontalGroup(
            jDesktopPaneControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneControleLayout.createSequentialGroup()
                .addGroup(jDesktopPaneControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneControleLayout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(jLabelBibliotheque))
                    .addGroup(jDesktopPaneControleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPaneControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneControleLayout.createSequentialGroup()
                                .addComponent(jButtonAjouterLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonSupprimerLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonDeco))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jDesktopPaneControleLayout.setVerticalGroup(
            jDesktopPaneControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneControleLayout.createSequentialGroup()
                .addComponent(jLabelBibliotheque, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouterLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonSupprimerLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPaneControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPaneControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterLivreActionPerformed
        // TODO add your handling code here:
   
        //Creer la fenetre pour creer le livre dans le PaneControle
        app.controleur.setjInternal(new JInternalFrameCreerLivre());
        this.jDesktopPaneControle.add(app.controleur.getjInternal());
        
        
       
        app.controleur.getjInternal().setControleur(app.controleur);
        app.controleur.getjInternal().setjFrame(this);
        
        
        // Ajouter les infos des tables format, edition, auteur et genre dans les menus déroulants
        try {
            ArrayList<TableAnnexe> tableFormat = app.tableLivres.lireTableAnnexe("format");
            ArrayList<TableAnnexe> tableEdition = app.tableLivres.lireTableAnnexe("edition");
            ArrayList<TableAnnexe> tableAuteur = app.tableLivres.lireTableAnnexe("auteur");
            ArrayList<TableAnnexe> tableGenre = app.tableLivres.lireTableAnnexe("genre");
            app.listIdAuteur = app.controleur.getjInternal().controleur.setComboBox(app.controleur.getjInternal().getjComboBoxAuteur(), tableAuteur);
            app.listIdEdition = app.controleur.getjInternal().controleur.setComboBox(app.controleur.getjInternal().getjComboBoxEdition(), tableEdition);
            app.listIdGenre = app.controleur.getjInternal().controleur.setComboBox(app.controleur.getjInternal().getjComboBoxGenre(), tableGenre);
            app.listIdFormat = app.controleur.getjInternal().controleur.setComboBox(app.controleur.getjInternal().getjComboBoxFormat(), tableFormat);

        } catch (SQLException ex) {
            Logger.getLogger(JFrameBibliotheque.class.getName()).log(Level.SEVERE, null, ex);
        }

        app.controleur.getjInternal().show();


    }//GEN-LAST:event_jButtonAjouterLivreActionPerformed

    private void jButtonDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecoActionPerformed

        
        app.controleur.deconnexion(this,app.jFrameConnexion);
       

    }//GEN-LAST:event_jButtonDecoActionPerformed

    private void jToggleButtonSupprimerLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSupprimerLivreActionPerformed
      
        int selectedRow = this.jTableBibliotheque.getSelectedRow();
        String idLivre = String.valueOf(this.jTableBibliotheque.getModel().getValueAt(selectedRow, 9));
        app.tableLivres.supprimerLivre(idLivre);
        app.majBiblio(app.tableLivres.lireLivresParID(app.admi.getIdUtilisateur()),app.admi);
    }//GEN-LAST:event_jToggleButtonSupprimerLivreActionPerformed

    public void setApp(App app) {
        this.app = app;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBibliotheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBibliotheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBibliotheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBibliotheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameBibliotheque().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterLivre;
    private javax.swing.JButton jButtonDeco;
    private javax.swing.JDesktopPane jDesktopPaneControle;
    private javax.swing.JLabel jLabelBibliotheque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBibliotheque;
    private javax.swing.JToggleButton jToggleButtonSupprimerLivre;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableBibliotheque() {
        return jTableBibliotheque;
    }
}
