/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import entities.Livre;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import services.CControleurJFrame;

/**
 *
 * @author SIO_7
 */
public class JInternalFrameCreerLivre extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameCreerLivre
     */
    public JInternalFrameCreerLivre() {
        initComponents();

    }

    CControleurJFrame controleur;
    JFrameBibliotheque jFrame;

    public JFrameBibliotheque getjFrame() {
        return jFrame;
    }

    public void setjFrame(JFrameBibliotheque jFrame) {
        this.jFrame = jFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextTitre = new javax.swing.JTextField();
        jTextRef = new javax.swing.JTextField();
        jTextPages = new javax.swing.JTextField();
        jTextAnneeEd = new javax.swing.JTextField();
        jButtonAjouterLivre = new javax.swing.JButton();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jComboBoxGenre = new javax.swing.JComboBox<>();
        jComboBoxAuteur = new javax.swing.JComboBox<>();
        jComboBoxEdition = new javax.swing.JComboBox<>();
        jTextLangue = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Créer livre");
        setOpaque(true);

        jLabel1.setText("Titre");

        jLabel2.setText("Auteur");

        jLabel3.setText("Référence ISBN");

        jLabel4.setText("Pages");

        jLabel5.setText("Édition");

        jLabel6.setText("Genre");

        jLabel7.setText("Année Édition");

        jLabel9.setText("Format");

        jTextTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTitreActionPerformed(evt);
            }
        });

        jButtonAjouterLivre.setText("Ajouter livre");
        jButtonAjouterLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterLivreActionPerformed(evt);
            }
        });

        jComboBoxAuteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAuteurActionPerformed(evt);
            }
        });

        jLabel8.setText("Langue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAjouterLivre)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextLangue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEdition, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxAuteur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxFormat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGenre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextRef, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPages, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTitre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jTextAnneeEd, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextAnneeEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonAjouterLivre)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTitreActionPerformed
       


    }//GEN-LAST:event_jTextTitreActionPerformed

    private void jButtonAjouterLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterLivreActionPerformed

        String titre = jTextTitre.getText();
        String auteur = String.valueOf(this.getjFrame().app.listIdAuteur.get(jComboBoxAuteur.getSelectedIndex()));;
        String ref = jTextRef.getText();
        String pages = jTextPages.getText();
        String edition = String.valueOf(this.getjFrame().app.listIdEdition.get(jComboBoxEdition.getSelectedIndex()));
        String genre = String.valueOf(this.getjFrame().app.listIdGenre.get(jComboBoxGenre.getSelectedIndex()));
        String anneeEd = jTextAnneeEd.getText();
        String format = String.valueOf(this.getjFrame().app.listIdFormat.get(jComboBoxFormat.getSelectedIndex()));
        String idPro = this.getjFrame().app.admi.getIdUtilisateur();
        String langue = jTextLangue.getText();
        Livre livre = new Livre(titre, auteur, ref, pages, edition, genre, anneeEd, format, idPro, langue);
        
        livre.afficher();
        if (controleur.insererLivreBouton(livre,this.getjFrame().app) > 0) {
            
            JOptionPane.showMessageDialog(null, "Le livre a été ajouté");
            this.getjFrame().app.majBiblio(this.getjFrame().app.tableLivres.lireLivresParID(this.getjFrame().app.admi.getIdUtilisateur()), this.getjFrame().app.admi);

        } else {

            JOptionPane.showMessageDialog(null, "Le livre n'a pas été ajouté");
        }

    }//GEN-LAST:event_jButtonAjouterLivreActionPerformed

    private void jComboBoxAuteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAuteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAuteurActionPerformed

    public void setControleur(CControleurJFrame controleur) {
        this.controleur = controleur;
    }

    public JComboBox<String> getjComboBoxAuteur() {
        return jComboBoxAuteur;
    }

    public void setjComboBoxAuteur(JComboBox<String> jComboBoxAuteur) {
        this.jComboBoxAuteur = jComboBoxAuteur;
    }

    public JComboBox<String> getjComboBoxEdition() {
        return jComboBoxEdition;
    }

    public void setjComboBoxEdition(JComboBox<String> jComboBoxEdition) {
        this.jComboBoxEdition = jComboBoxEdition;
    }

    public JComboBox<String> getjComboBoxFormat() {
        return jComboBoxFormat;
    }

    public void setjComboBoxFormat(JComboBox<String> jComboBoxFormat) {
        this.jComboBoxFormat = jComboBoxFormat;
    }

    public JComboBox<String> getjComboBoxGenre() {
        return jComboBoxGenre;
    }

    public void setjComboBoxGenre(JComboBox<String> jComboBoxGenre) {
        this.jComboBoxGenre = jComboBoxGenre;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterLivre;
    private javax.swing.JComboBox<String> jComboBoxAuteur;
    private javax.swing.JComboBox<String> jComboBoxEdition;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JComboBox<String> jComboBoxGenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextAnneeEd;
    private javax.swing.JTextField jTextLangue;
    private javax.swing.JTextField jTextPages;
    private javax.swing.JTextField jTextRef;
    private javax.swing.JTextField jTextTitre;
    // End of variables declaration//GEN-END:variables
}
